#!/usr/bin/with-contenv bash

cat <<EOF
---
qbit-matUI Theme Installer
Source: https://github.com/bill-ahmed/qbit-matUI
---
EOF

LATEST_RELEASE=$(curl -s -L https://api.github.com/repos/bill-ahmed/qbit-matUI/releases/latest |
  grep "browser_download_url.*Unix.*zip" |
  cut -d : -f 2,3 |
  tr -d \" |
  xargs) # to trim whitespace

if [ ! -d /qbit-matui ]; then
  echo "Running installer..."

  curl -o qbit-matui.zip -L $LATEST_RELEASE &&
    unzip qbit-matui.zip -d /

  # Remove zip after unpacking
  rm /qbit-matui.zip

  mv /qbit-mat* /qbit-matui

  echo "Done! The theme is installed in the root folder. Apply it from WEBUI settings."
else
  echo "qbit-matUI theme is already installed. Exiting..."
fi

APP_FILEPATH='/config/qBittorrent/qBittorrent.conf'

if ! grep -q "WebUI\\\RootFolder" "${APP_FILEPATH}"; then
    echo '--------------------------------------'
    echo '| Adding WebUI\RootFolder=/qbit-matui |'
    echo '--------------------------------------'
    sed -i -e '$aWebUI\\RootFolder=/qbit-matui' "${APP_FILEPATH}"
fi

if ! grep -q "WebUI\\\AlternativeUIEnabled" "${APP_FILEPATH}"; then
    echo '------------------------------------------'
    echo '| Adding WebUI\AlternativeUIEnabled=true |'
    echo '------------------------------------------'
    sed -i -e '$aWebUI\\AlternativeUIEnabled=true' "${APP_FILEPATH}"
fi

if ! grep -q "WebUI\\\RootFolder=/qbit-matui" "${APP_FILEPATH}" || ! grep -q "WebUI\\\AlternativeUIEnabled=true" "${APP_FILEPATH}"; then
    echo '-------------------------------------------------------'
    echo '| Updating RootFolder and AlternativeUIEnabled values |'
    echo '-------------------------------------------------------'
    sed -i "s/WebUI\\\AlternativeUIEnabled=.*$/WebUI\\\AlternativeUIEnabled=true/g" "${APP_FILEPATH}"
    sed -i "s/WebUI\\\RootFolder=.*$/WebUI\\\RootFolder=\/qbit-matui/g" "${APP_FILEPATH}"
fi
